# Ore framework - SPIR-V -> C++ header embedding script.
#
# Invoked at build time as:  cmake -DINPUT=<a.spv;b.spv> -DOUTPUT=<header> -DNAME_SPACE=ore::embedded -P EmbedSpirv.cmake
#
# Produces a header with one std::array per shader plus a table that can be handed to
# ore::shader_registry::add_blobs() so a build can run without shipping .spv files.

if(NOT INPUT)
    message(FATAL_ERROR "EmbedSpirv.cmake: INPUT (list of .spv files) is required")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "EmbedSpirv.cmake: OUTPUT (header path) is required")
endif()
if(NOT NAME_SPACE)
    set(NAME_SPACE "ore::embedded")
endif()

set(_decls "")
set(_entries "")
foreach(_spv IN LISTS INPUT)
    get_filename_component(_file "${_spv}" NAME)
    file(READ "${_spv}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _word_count "${_hex_len} / 8")

    # Sanitize the shader file name into a C++ identifier: cube.vert.spv -> cube_vert_spv
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" _ident "${_file}")
    if(_ident MATCHES "^[0-9]")
        set(_ident "shader_${_ident}")
    endif()

    set(_words "")
    set(_i 0)
    while(_i LESS _word_count)
        math(EXPR _off "${_i} * 8")
        string(SUBSTRING "${_hex}" ${_off} 8 _word)
        # SPIR-V words are little endian in memory; emit them as host-order 32 bit literals.
        string(SUBSTRING "${_word}" 6 2 _b0)
        string(SUBSTRING "${_word}" 4 2 _b1)
        string(SUBSTRING "${_word}" 2 2 _b2)
        string(SUBSTRING "${_word}" 0 2 _b3)
        string(APPEND _words "0x${_b0}${_b1}${_b2}${_b3}u,")
        math(EXPR _i "${_i} + 1")
    endwhile()

    string(APPEND _decls "inline constexpr std::uint32_t ${_ident}[] = {${_words}};\n")
    string(APPEND _entries "    {\"${_file}\", ${_ident}, sizeof(${_ident})},\n")
endforeach()

set(_guard "ORE_GENERATED_EMBEDDED_SHADERS_H")
file(WRITE "${OUTPUT}" "// Generated by cmake/EmbedSpirv.cmake - do not edit.
#pragma once
#include <cstddef>
#include <cstdint>
#include <ore/rhi/shader.h>

namespace ${NAME_SPACE} {

${_decls}
inline constexpr ore::ShaderBlob kAllShaders[] = {
${_entries}};

} // namespace ${NAME_SPACE}
")
message(STATUS "Embedded ${_file_count} shader(s) into ${OUTPUT}")
